import type { ImportBundle } from "./_types";

export const demoData: ImportBundle = {
  clients: [
    {
      client_key: "acme_trading",
      display_name: "Acme Trading",
      type: "LEGAL_ENTITY",
      constitution: "PROPRIETORSHIP",
      legal_name: "Acme Trading and Sons",
      pan: "AAAPA1234A",
      primary_phone: "+919876543210",
      website: "https://acme.example",
      residency: "RESIDENT",
      group_name: "Acme Group",
      portal_email: "accounts@acme.example",
      status_key: "active",
      is_director_or_partner_audit_liable: false,
    },
    {
      client_key: "bluewave_labs",
      display_name: "Bluewave Labs Private Limited",
      type: "LEGAL_ENTITY",
      constitution: "PRIVATE_LIMITED_COMPANY",
      legal_name: "Bluewave Labs Private Limited",
      pan: "AAACB5678K",
      gstin: "27AAACB5678K1ZX",
      cin: "U72900MH2022PTC123456",
      residency: "RESIDENT",
      portal_email: "finance@bluewave.example",
      status_key: "active",
      is_director_or_partner_audit_liable: true,
    },
    {
      client_key: "rahul_sharma",
      display_name: "Rahul Sharma",
      type: "INDIVIDUAL",
      constitution: "INDIVIDUAL",
      legal_name: "Rahul Sharma",
      pan: "ABCDE1234F",
      primary_phone: "+919876543211",
      residency: "RESIDENT",
      status_key: "active",
      is_director_or_partner_audit_liable: false,
    },
  ],
  clientLocations: [
    {
      client_key: "acme_trading",
      location_key: "acme_registered_office",
      location_name: "Registered Office",
      location_type: "registered_office",
      line1: "12 MG Road",
      area: "Andheri East",
      city: "Mumbai",
      state: "Maharashtra",
      postal_code: "400001",
      country_code: "IN",
      is_primary: true,
    },
    {
      client_key: "acme_trading",
      location_key: "acme_factory",
      location_name: "Factory",
      location_type: "factory",
      line1: "Plot 4 MIDC",
      area: "Satpur",
      city: "Nashik",
      state: "Maharashtra",
      postal_code: "422007",
      country_code: "IN",
      is_primary: false,
    },
  ],
  clientContacts: [
    {
      client_key: "acme_trading",
      contact_key: "acme_accounts",
      given_name: "Meera",
      family_name: "Shah",
      email: "meera@acme.example",
      phone: "+919876543210",
      is_primary_contact: true,
      is_billing_contact: true,
      is_service_contact: true,
      designation_key: "accounts_manager",
    },
    {
      client_key: "bluewave_labs",
      contact_key: "bluewave_finance",
      given_name: "Arjun",
      family_name: "Patel",
      email: "arjun@bluewave.example",
      phone: "+919876543220",
      is_primary_contact: true,
      is_billing_contact: true,
      is_service_contact: false,
      designation_key: "finance_manager",
    },
  ],
  clientRegistrations: [
    {
      client_key: "acme_trading",
      registration_key: "acme_gstin",
      type: "GSTIN",
      registration_number: "27AAAPA1234A1Z5",
      effective_from: "2026-04-01",
      status: "active",
      is_principal: true,
      legal_name: "Acme Trading and Sons",
      trade_name: "Acme Trading",
      authority: "State GST Department",
      jurisdiction: "Maharashtra",
    },
    {
      client_key: "acme_trading",
      registration_key: "acme_tan",
      type: "TAN",
      registration_number: "ABCD12345E",
      effective_from: "2026-04-01",
      status: "active",
      is_principal: false,
      legal_name: "Acme Trading and Sons",
      jurisdiction: "Maharashtra",
    },
  ],
  clientMemberships: [],
  clientRegistrationLocations: [],
  clientComplianceReferences: [],
  clientBillToParties: [],
  clientEmployeeAssignments: [],
  clientServiceEngagements: [],
  services: [
    {
      service_key: "income_tax_return",
      name: "Income Tax Return",
      is_non_gst: false,
      hsn_sac_code: "998231",
      classification_kind: "SAC",
      classification_description: "Income tax return preparation",
      default_billable: false,
      default_hourly_rate: 1500,
      gst_applicability_date: "2026-04-01",
      taxability: "TAXABLE",
      cgst_rate: 9,
      sgst_rate: 9,
      igst_rate: 18,
      reverse_charge_applicable: false,
    },
    {
      service_key: "gst_registration",
      name: "GST Registration",
      is_non_gst: false,
      hsn_sac_code: "998599",
      classification_kind: "SAC",
      classification_description: "GST registration and amendment services",
      default_billable: false,
      default_hourly_rate: 1200,
      gst_applicability_date: "2026-04-01",
      taxability: "TAXABLE",
      cgst_rate: 9,
      sgst_rate: 9,
      igst_rate: 18,
      reverse_charge_applicable: false,
    },
    {
      service_key: "internal_advisory",
      name: "Internal Advisory",
      is_non_gst: true,
      default_billable: false,
      default_hourly_rate: 1800,
    },
    {
      service_key: "charitable_trust_audit",
      name: "Charitable Trust Audit",
      is_non_gst: false,
      hsn_sac_code: "998221",
      classification_kind: "SAC",
      classification_description: "Audit of charitable institutions",
      default_billable: true,
      default_hourly_rate: 2500,
      gst_applicability_date: "2026-04-01",
      taxability: "EXEMPTED",
      cgst_rate: 0,
      sgst_rate: 0,
      igst_rate: 0,
      reverse_charge_applicable: false,
    },
  ],
  serviceGstHistory: [
    {
      service_template_id: "",
      service_key: "income_tax_return",
      gst_history_key: "income_tax_return_2026",
      applicability_date: "2026-04-01",
      taxability: "TAXABLE",
      cgst_rate: 9,
      sgst_rate: 9,
      igst_rate: 18,
      reverse_charge_applicable: false,
    },
  ],
  serviceFrequencyRates: [
    {
      service_template_id: "",
      service_key: "income_tax_return",
      frequency_key: "annual",
      hourly_rate: 1500,
    },
  ],
  serviceCustomFields: [],
  serviceTasks: [
    {
      service_key: "income_tax_return",
      task_key: "collect_documents",
      label: "Collect supporting documents",
      sort_order: 1,
      expected_minutes: 45,
      due_date_offset_days: 5,
      frequency_key: "annual",
      operational_role_key: "preparer",
      requires_verification: false,
      is_active: true,
    },
    {
      service_key: "income_tax_return",
      task_key: "prepare_return",
      label: "Prepare return",
      sort_order: 2,
      expected_minutes: 120,
      due_date_offset_days: 10,
      frequency_key: "annual",
      operational_role_key: "preparer",
      requires_verification: false,
      is_active: true,
    },
    {
      service_key: "income_tax_return",
      task_key: "review_return",
      label: "Review return",
      sort_order: 3,
      expected_minutes: 60,
      due_date_offset_days: 15,
      frequency_key: "annual",
      operational_role_key: "reviewer",
      requires_verification: true,
      is_active: true,
    },
    {
      service_key: "income_tax_return",
      task_key: "review_documents",
      parent_task_key: "review_return",
      label: "Review supporting documents",
      sort_order: 1,
      expected_minutes: 30,
      due_date_offset_days: 16,
      frequency_key: "annual",
      operational_role_key: "reviewer",
      requires_verification: true,
      is_active: true,
    },
  ],
  serviceDependencies: [
    {
      service_key: "income_tax_return",
      predecessor_task_key: "collect_documents",
      successor_task_key: "prepare_return",
    },
    {
      service_key: "income_tax_return",
      predecessor_task_key: "prepare_return",
      successor_task_key: "review_return",
    },
  ],
};
