import ExcelJS from "exceljs";

import type { ImportBundle, ValidationIssue } from "./_types";
import { demoData } from "./demo";
import { COLUMNS, SHEETS } from "./schema";
import { validateBundle } from "./validation";

const sheetMap = {
  Clients: "clients",
  ClientLocations: "clientLocations",
  ClientContacts: "clientContacts",
  ClientRegistrations: "clientRegistrations",
  ClientMemberships: "clientMemberships",
  ClientRegistrationLocations: "clientRegistrationLocations",
  ClientComplianceReferences: "clientComplianceReferences",
  ClientBillToParties: "clientBillToParties",
  ClientEmployeeAssignments: "clientEmployeeAssignments",
  ClientServiceEngagements: "clientServiceEngagements",
  Services: "services",
  ServiceGstHistory: "serviceGstHistory",
  ServiceFrequencyRates: "serviceFrequencyRates",
  ServiceCustomFields: "serviceCustomFields",
  ServiceTasks: "serviceTasks",
  ServiceDependencies: "serviceDependencies",
} as const;
const VALIDATION_ROW_LIMIT = 100;

export async function createWorkbook(
  data: ImportBundle = demoData,
  selectedSheets: readonly (typeof SHEETS)[number][] = defaultSheets(data),
): Promise<Uint8Array> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "ERP VDA CA";
  const readme = workbook.addWorksheet("README");
  readme.addRow(["Client and Service Excel Import/Export"]);
  readme.addRow([
    "Fill the input sheets from row 6. Required headers are marked [required]. Hover the readable headers for help. ValidationReport and Rulebook are generated by the application.",
  ]);
  readme.getRow(1).font = { bold: true, size: 16 };
  readme.getRow(1).height = 30;
  readme.getRow(2).height = 30;
  readme.getColumn(1).width = 110;
  if (selectedSheets.includes("Clients"))
    workbook.definedNames.add("Clients!$A$6:$A$1000", "ClientKeys");
  if (selectedSheets.includes("Services"))
    workbook.definedNames.add("Services!$A$6:$A$1000", "ServiceKeys");
  selectedSheets.forEach((sheetName) => {
    const sheet = workbook.addWorksheet(sheetName);
    const columns = COLUMNS[sheetName].filter((column) => !hiddenByDefault(column.key));
    columns.forEach((column, index) => {
      const row = index + 1;
      sheet.mergeCells(1, row, 2, row);
      const cell = sheet.getCell(1, row);
      cell.value = column.header;
      sheet.getColumn(index + 1).width = Math.min(
        44,
        Math.max(16, Math.max(column.header.length, humanizeHeader(column.header).length) + 4),
      );
      sheet.getColumn(index + 1).hidden = hiddenByDefault(column.key);
    });
    sheet.mergeCells(3, 1, 3, columns.length);
    sheet.getCell(3, 1).value =
      `${sheetName}: enter one record per row starting at row 6. Hover a readable header for input guidance. Do not rename or reorder the technical headers.`;
    columns.forEach((column, index) => {
      const row = index + 1;
      sheet.mergeCells(4, row, 5, row);
      const cell = sheet.getCell(4, row);
      cell.value = humanizeHeader(column.header);
      cell.note = columnHelp(column);
    });
    for (let index = 1; index <= columns.length; index += 1) {
      const technicalHeader = sheet.getCell(1, index);
      technicalHeader.font = { bold: true, color: { argb: "7F1D1D" } };
      technicalHeader.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FEE2E2" } };
      technicalHeader.alignment = { horizontal: "center", vertical: "middle", wrapText: true };
    }
    sheet.getRow(1).height = 30;
    for (let index = 1; index <= columns.length; index += 1) {
      const readableHeader = sheet.getCell(4, index);
      readableHeader.font = { bold: true, color: { argb: "FFFFFF" } };
      readableHeader.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "334155" } };
      readableHeader.alignment = { horizontal: "center", vertical: "middle", wrapText: true };
    }
    sheet.getRow(4).height = 30;
    sheet.getRow(5).height = 30;
    sheet.getRow(2).font = { color: { argb: "7F1D1D" } };
    sheet.getRow(3).font = { color: { argb: "64748B" }, size: 10 };
    sheet.getRow(3).alignment = { wrapText: true };
    sheet.views = [{ state: "frozen", ySplit: 5 }];
    const rows = data[sheetMap[sheetName]];
    rows.forEach((row) => sheet.addRow(columns.map((column) => sanitizeCell(row[column.key]))));
    sheet.autoFilter = {
      from: "A4",
      to: `${columnLetter(columns.length)}${Math.max(5, rows.length + 5)}`,
    };
    columns.forEach((column, index) => {
      if (
        [
          "client_key",
          "location_key",
          "contact_key",
          "registration_key",
          "service_key",
          "task_key",
          "parent_task_key",
          "predecessor_task_key",
          "successor_task_key",
          "pan",
          "tan",
          "gstin",
          "cin",
          "llpin",
          "postal_code",
        ].includes(column.key)
      )
        sheet.getColumn(index + 1).numFmt = "@";
      if (column.enum)
        (sheet.getColumn(index + 1) as unknown as { dataValidation: unknown }).dataValidation = {
          type: "list",
          allowBlank: !column.required,
          formulae: [`"${column.enum.join(",")}"`],
          error: "Choose a value from the list.",
          errorTitle: "Invalid value",
          showErrorMessage: true,
        };
    });
    applyRelationshipRules(workbook, sheet, sheetName, columns, selectedSheets);
  });
  const report = workbook.addWorksheet("ValidationReport");
  report.addRow(["severity", "code", "sheet", "row", "column", "header", "value", "message"]);
  for (let index = 1; index <= 8; index += 1) {
    const header = report.getCell(1, index);
    header.font = { bold: true, color: { argb: "7F1D1D" } };
    header.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FEE2E2" } };
  }
  report.getRow(1).height = 30;
  report.views = [{ state: "frozen", ySplit: 1 }];
  addRulebook(workbook, selectedSheets);
  return new Uint8Array((await workbook.xlsx.writeBuffer()) as unknown as ArrayBuffer);
}

function columnLetter(number: number): string {
  let result = "";
  let current = number;
  while (current > 0) {
    const remainder = (current - 1) % 26;
    result = String.fromCharCode(65 + remainder) + result;
    current = Math.floor((current - 1) / 26);
  }
  return result;
}

function defaultSheets(data: ImportBundle): (typeof SHEETS)[number][] {
  return SHEETS.filter(
    (sheet) => sheet === "Clients" || sheet === "Services" || data[sheetMap[sheet]].length > 0,
  );
}
function humanizeHeader(header: string): string {
  return header
    .replace(/\s*\[required\]\s*$/u, "")
    .split("_")
    .map((part) => (part ? part[0].toUpperCase() + part.slice(1) : part))
    .join(" ");
}

function columnHelp(column: {
  key: string;
  required?: boolean;
  type?: string;
  enum?: readonly string[];
}): string {
  const relationship = [
    "client_key",
    "service_key",
    "parent_task_key",
    "predecessor_task_key",
    "successor_task_key",
    "location_key",
    "registration_key",
    "contact_key",
  ].includes(column.key);
  const required = column.required
    ? "Required. "
    : "Optional. Leave blank when it does not apply. ";
  const type = column.enum
    ? `Choose one of: ${column.enum.join(", ")}. `
    : column.type === "boolean"
      ? "Enter true or false. "
      : column.type === "date"
        ? "Enter a valid date as YYYY-MM-DD. "
        : column.type === "number"
          ? "Enter a numeric value, not text. "
          : "Enter plain text. ";
  const relation = relationship
    ? "This key must match the related record in its parent sheet; Excel highlights missing relationships in red. "
    : "";
  return `${required}${type}${relation}The user enters this value.`;
}

function hiddenByDefault(key: string): boolean {
  return [
    "client_id",
    "contact_id",
    "location_id",
    "registration_id",
    "service_template_id",
    "organization_id",
    "financial_year_id",
    "user_id",
    "embedded_addresses",
    "statutory_identifiers",
    "email_points",
    "phone_points",
    "scope_snapshot",
    "role_assignments",
    "node_assignments",
    "client_payments",
    "select_options",
    "task_node_id",
    "parent_task_node_id",
    "predecessor_node_id",
    "successor_node_id",
  ].includes(key);
}

function addRulebook(workbook: ExcelJS.Workbook, selectedSheets: readonly string[]): void {
  const sheet = workbook.addWorksheet("Rulebook");
  sheet.addRow(["Workbook rulebook"]);
  sheet.addRow([
    "Use the technical keys in rows 1–2 for import. Readable labels are in rows 4–5. Enter data from row 6 onward.",
  ]);
  sheet.addRow([]);
  sheet.addRow(["Sheet", "Purpose", "Column", "Who fills it", "Rules and accepted values"]);
  selectedSheets.forEach((name) => {
    const columns = COLUMNS[name as keyof typeof COLUMNS].filter(
      (column) => !hiddenByDefault(column.key),
    );
    columns.forEach((column, index) =>
      sheet.addRow([
        index === 0 ? name : "",
        index === 0 ? rulebookPurpose(name) : "",
        humanizeHeader(column.header),
        "User",
        columnHelp(column),
      ]),
    );
  });
  sheet.addRow([]);
  sheet.addRow([
    "Common rules",
    "Required values cannot be blank. Optional values must be blank rather than placeholder text. Keys must be stable and unique. Dates must be valid ISO dates or Excel dates. Booleans must be true or false. Formula values are rejected. Relationship keys must resolve to the appropriate parent record. Import is atomic: a blocking error prevents every write.",
  ]);
  sheet.addRow([
    "Update exports",
    "When a future round-trip export includes IDs and revision values, those are system-managed. Ordinary templates do not show them and users never type them manually.",
  ]);
  sheet.addRow([
    "ValidationReport",
    "Generated by the application. ERROR rows block import. WARNING rows are review items. It shows sheet, row, column, input value, stable error code, and a plain-language correction. Do not edit it as source data.",
  ]);
  sheet.mergeCells(1, 1, 1, 5);
  sheet.mergeCells(2, 1, 2, 5);
  sheet.getRow(1).height = 30;
  sheet.getRow(2).height = 30;
  sheet.getRow(4).height = 30;
  for (let index = 1; index <= 5; index += 1) {
    const title = sheet.getCell(1, index);
    title.font = { bold: true, size: 16, color: { argb: "7F1D1D" } };
    title.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FEE2E2" } };
    const header = sheet.getCell(4, index);
    header.font = { bold: true, color: { argb: "FFFFFF" } };
    header.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "334155" } };
  }
  sheet.columns = [{ width: 30 }, { width: 44 }, { width: 28 }, { width: 18 }, { width: 90 }];
  sheet.eachRow((row) => {
    row.alignment = { vertical: "top", wrapText: true };
  });
  sheet.views = [{ state: "frozen", ySplit: 4 }];
}

function rulebookPurpose(sheet: string): string {
  return (
    (
      {
        Clients: "Client master data and safe portal/communication state.",
        ClientLocations: "Client addresses and operating locations.",
        ClientContacts: "Reusable contacts with reversible email and phone points.",
        ClientRegistrations: "GSTIN/TAN and statutory registration records.",
        ClientMemberships: "Links a client, contact, designation, access role, and contact flags.",
        ClientRegistrationLocations: "Links registrations to valid client locations.",
        ClientComplianceReferences: "Financial-year compliance references for a client.",
        ClientBillToParties: "Billing recipients, GST mode, and billing address.",
        ClientEmployeeAssignments: "Internal user operational roles for a client.",
        ClientServiceEngagements:
          "Client-specific service scope, billing, recipients, tasks, roles, and payments.",
        Services: "Service template master data and current service policy.",
        ServiceGstHistory: "One row per GST rate history entry.",
        ServiceFrequencyRates: "Frequency-specific hourly rate overrides.",
        ServiceCustomFields: "Service/task custom fields and reversible options.",
        ServiceTasks: "Embedded service task nodes and parent-child structure.",
        ServiceDependencies: "Predecessor/successor dependencies between service task nodes.",
      } as Record<string, string>
    )[sheet] ?? "Workbook data."
  );
}
function rulebookRules(sheet: string): string {
  if (sheet.startsWith("Client") && sheet !== "Clients")
    return "client_id/client_key must resolve to the stated client. IDs and keys must agree when both are present.";
  if (sheet.startsWith("Service") && sheet !== "Services")
    return "service_template_id/service_key must resolve to the stated service. Task parents and dependencies must remain within the same service and stay acyclic.";
  return "Keys are unique. Existing IDs are authoritative. IDs, revisions, and status controls support safe round-trip updates.";
}

function applyRelationshipRules(
  workbook: ExcelJS.Workbook,
  sheet: ExcelJS.Worksheet,
  sheetName: string,
  columns: readonly { key: string }[],
  selectedSheets: readonly string[],
): void {
  const indexOf = (key: string) => columns.findIndex((column) => column.key === key) + 1;
  const addReference = (key: string, rangeName: string, message: string) => {
    const index = indexOf(key);
    if (!index) return;
    const letter = columnLetter(index);
    for (let row = 6; row <= VALIDATION_ROW_LIMIT; row += 1)
      sheet.getCell(row, index).dataValidation = {
        type: "custom",
        allowBlank: true,
        formulae: [`=OR(${letter}${row}=\"\",COUNTIF(${rangeName},${letter}${row})>0)`],
        error: message,
        errorTitle: "Relationship not found",
        prompt: "Use a key from the related sheet.",
        promptTitle: "Reference key",
        showErrorMessage: true,
        showInputMessage: true,
      };
    sheet.addConditionalFormatting({
      ref: `${letter}6:${letter}${VALIDATION_ROW_LIMIT}`,
      rules: [
        {
          type: "expression",
          priority: 1,
          formulae: [`=AND(${letter}6<>\"\",COUNTIF(${rangeName},${letter}6)=0)`],
          style: {
            fill: { type: "pattern", pattern: "solid", fgColor: { argb: "FECACA" } },
            font: { color: { argb: "991B1B" } },
          },
        },
      ],
    });
  };
  if (
    ["ClientLocations", "ClientContacts", "ClientRegistrations"].includes(sheetName) &&
    selectedSheets.includes("Clients")
  )
    addReference("client_key", "ClientKeys", "Client key does not exist on the Clients sheet.");
  if (
    ["ServiceTasks", "ServiceDependencies"].includes(sheetName) &&
    selectedSheets.includes("Services")
  )
    addReference("service_key", "ServiceKeys", "Service key does not exist on the Services sheet.");
  if (sheetName === "ServiceTasks") {
    const parent = indexOf("parent_task_key");
    if (parent) {
      const key = columnLetter(parent);
      sheet.addConditionalFormatting({
        ref: `${key}6:${key}${VALIDATION_ROW_LIMIT}`,
        rules: [
          {
            type: "expression",
            priority: 2,
            formulae: [
              `=AND(${key}6<>\"\",COUNTIFS($A$6:$A$${VALIDATION_ROW_LIMIT},$A6,$B$6:$B$${VALIDATION_ROW_LIMIT},${key}6)=0)`,
            ],
            style: {
              fill: { type: "pattern", pattern: "solid", fgColor: { argb: "FECACA" } },
              font: { color: { argb: "991B1B" } },
            },
          },
        ],
      });
    }
  }
  if (sheetName === "ServiceDependencies") {
    const service = indexOf("service_key");
    const pre = indexOf("predecessor_task_key");
    const suc = indexOf("successor_task_key");
    if (service && pre && suc) {
      const s = columnLetter(service);
      for (const index of [pre, suc]) {
        const key = columnLetter(index);
        sheet.addConditionalFormatting({
          ref: `${key}6:${key}${VALIDATION_ROW_LIMIT}`,
          rules: [
            {
              type: "expression",
              priority: 3,
              formulae: [
                `=AND(${key}6<>\"\",COUNTIFS($A$6:$A$${VALIDATION_ROW_LIMIT},${s}6,$B$6:$B$${VALIDATION_ROW_LIMIT},${key}6)=0)`,
              ],
              style: {
                fill: { type: "pattern", pattern: "solid", fgColor: { argb: "FECACA" } },
                font: { color: { argb: "991B1B" } },
              },
            },
          ],
        });
      }
    }
  }
}

export const CLIENT_SHEETS = [
  "Clients",
  "ClientLocations",
  "ClientContacts",
  "ClientRegistrations",
  "ClientMemberships",
  "ClientRegistrationLocations",
  "ClientComplianceReferences",
  "ClientBillToParties",
  "ClientEmployeeAssignments",
  "ClientServiceEngagements",
] as const;
export const SERVICE_SHEETS = [
  "Services",
  "ServiceGstHistory",
  "ServiceFrequencyRates",
  "ServiceCustomFields",
  "ServiceTasks",
  "ServiceDependencies",
] as const;
export async function createClientWorkbook(data: ImportBundle = demoData): Promise<Uint8Array> {
  return createWorkbook(data, activeSheets(data, CLIENT_SHEETS, "Clients"));
}
export async function createServiceWorkbook(data: ImportBundle = demoData): Promise<Uint8Array> {
  return createWorkbook(data, activeSheets(data, SERVICE_SHEETS, "Services"));
}

function activeSheets(
  data: ImportBundle,
  candidates: readonly (typeof SHEETS)[number][],
  primary: (typeof SHEETS)[number],
): (typeof SHEETS)[number][] {
  return candidates.filter(
    (sheet) => sheet === primary || data[sheetMap[sheet]].length > 0,
  ) as (typeof SHEETS)[number][];
}

export async function createDemoWorkbook(): Promise<Uint8Array> {
  return createWorkbook(demoData);
}

export async function parseWorkbook(
  bytes: Uint8Array,
  expectedSheets?: readonly (typeof SHEETS)[number][],
): Promise<{ data: ImportBundle; issues: ValidationIssue[] }> {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(
    Buffer.from(bytes) as unknown as Parameters<typeof workbook.xlsx.load>[0],
  );
  const data = emptyData();
  const issues: ValidationIssue[] = [];
  const sheetsToParse =
    expectedSheets ?? SHEETS.filter((name) => Boolean(workbook.getWorksheet(name)));
  sheetsToParse.forEach((name) => {
    const sheet = workbook.getWorksheet(name);
    if (!sheet) {
      issues.push({
        severity: "ERROR",
        code: "INVALID_FORMAT",
        sheet: name,
        row: 1,
        column: 1,
        header: "",
        value: "",
        message: `Missing worksheet ${name}.`,
      });
      return;
    }
    const sourceColumns = COLUMNS[name];
    const headerRow = sheet.getRow(1);
    const headers = (headerRow.values as unknown[])
      .slice(1)
      .map((value: unknown) => String(value ?? "").trim());
    const seen = new Set<string>();
    headers.forEach((header, i) => {
      const key = header.replace(/\s*\[required\]\s*$/u, "").trim();
      if (seen.has(key))
        issues.push({
          severity: "ERROR",
          code: "DUPLICATE_COLUMN",
          sheet: name,
          row: 4,
          column: i + 1,
          header,
          value: header,
          message: "Column header is duplicated.",
        });
      seen.add(key);
      if (!sourceColumns.some((column) => column.header === header))
        issues.push({
          severity: "ERROR",
          code: "UNKNOWN_COLUMN",
          sheet: name,
          row: 4,
          column: i + 1,
          header,
          value: header,
          message: "Column is not part of the workbook contract.",
        });
    });
    const columnEntries = headers
      .map((header, index) => ({
        column: sourceColumns.find((candidate) => candidate.header === header),
        index,
      }))
      .filter((entry): entry is { column: (typeof sourceColumns)[number]; index: number } =>
        Boolean(entry.column),
      );
    const rows = data[sheetMap[name]];
    for (let rowNo = 6; rowNo <= sheet.rowCount; rowNo++) {
      const row = sheet.getRow(rowNo);
      if (
        (row.values as unknown[])
          .slice(1)
          .every(
            (value: unknown) =>
              value === null || value === undefined || String(value).trim() === "",
          )
      )
        continue;
      const item: Record<string, unknown> = {};
      columnEntries.forEach(({ column, index }) => {
        const cell = row.getCell(index + 1);
        if (cell.type === ExcelJS.ValueType.Formula)
          issues.push({
            severity: "ERROR",
            code: "INVALID_TYPE",
            sheet: name,
            row: rowNo,
            column: index + 1,
            header: column.header,
            value: cell.value,
            message: "Formulas are not accepted in input cells.",
          });
        item[column.key] = cell.type === ExcelJS.ValueType.Date ? cell.value : cell.value;
      });
      rows.push(item);
    }
  });
  const result = validateBundle(data);
  return { data: result.data, issues: [...issues, ...result.issues] };
}

export function validationReportRows(issues: readonly ValidationIssue[]): (string | number)[][] {
  return issues.map((issue) => [
    issue.severity,
    issue.code,
    issue.sheet,
    issue.row,
    issue.column,
    issue.header,
    String(issue.value ?? ""),
    issue.message,
  ]);
}
export function emptyData(): ImportBundle {
  return {
    clients: [],
    clientLocations: [],
    clientContacts: [],
    clientRegistrations: [],
    clientMemberships: [],
    clientRegistrationLocations: [],
    clientComplianceReferences: [],
    clientBillToParties: [],
    clientEmployeeAssignments: [],
    clientServiceEngagements: [],
    services: [],
    serviceGstHistory: [],
    serviceFrequencyRates: [],
    serviceCustomFields: [],
    serviceTasks: [],
    serviceDependencies: [],
  };
}
function sanitizeCell(value: unknown): unknown {
  if (typeof value !== "string") return value ?? null;
  return /^[=+\-@]/u.test(value) ? `'${value}` : value;
}
